---
title: "ES6 일곱번째 시간 -  Promise -then, catch, chaining ... "
date: 2021-01-09
tags: JavaScript
toc : true
toc_sticky: true
---
## Promise -then 그리고 catch

<p>
 promise(resolve, reject) 를 실행해서 전달된 결과값이<br/>
 then(func1 , func2) 로 각각 인자로 전달된 함수가 실행된다.
 </p>

```js
{
// 랜덤값을 얻는 
  function nextInt(Max){
      return Math.floor(Math.random()*Max);
  }
  function getNotice(id){
      console.log("요청");

      return new Promise((resolve,reject) =>{
          setTimeout(function(){

              let notice = {id:1, title:"공지사항 prokise", content:"hehe"};
              let value =nextInt(10);
              try{
                  if(value>5)
                  throw new Error("너무 큰 수");
              }
              catch(msg){
                  reject({status:"tlfvo",message:"too big"});
              }
                  resolve(notice);

          },10000);
      });

  }

  let aa = getNotice(2); // 오랜시간을 먹는 함수 : 응답없음

  aa.then(
      function(value){
          console.log(value); // 결과 값을 가져오면 실행되는 코드
      },
      function(error){
          console.log(error);
      })
  console.log("메인 스레드는 계속 된다.");

}
```
## Promise Chaining  

* then을 통해 수행된 결과를 다음 then에게 return으로 넘길 수 있다. 새로운 프로미스 객체가 반환됨
* 꼬리에 꼬리를 물고있는 then절은 모두 실행이 된다. 리턴값이 없으면 undefind를 넘긴다.
* 앞선 then절이 오류가 나도 다음 then절에 첫번쨰 함수가 받는다. 이 오류는 catch절로 잡아야 한다.

```js
 {
    function getNotice(page){
        return new Promise((resolve, reject)=>{
            setTimeout(function(){
                let notice = {id:1, title:"notice title"};
                //resolve(notice);
                reject("aaaa");
                console.log("작업완료");
            }, 1000);
        });
    }

    //let notice = getNotice();
    let p = getNotice(1);
    //-----------------------
    p
    .then(
        notice=>{
            console.log("resolve 1 작업");
            console.log(notice);
            return notice.title;
        },
        reason=>{
            console.log("reject 1 작업"); // 결과값으로 reject를 반환받고 "reject 1 작업" 이 실행된다.
            console.log(reason);
        }
    )
    .catch(
        reason=>{
            console.log("catch1" + reason)
        }
    )
    .then(
        title=>{
            console.log("resolve 2 작업"); // resolve 2 작업
            console.log(title);            // undefined
            return title.length;           // 앞선 then절에서 title을 넘겨받지 않아 오류가 난다.
        },
        reason=>{
            console.log("reject 2 작업");
            console.log(reason);
        }
    )
    .catch(
        reason=>{
            console.log("catch2" + reason) 
            //이 오류를 catch절이 잡는다. "catch2TypeError: Cannot read property 'length' of undefined"
        }
    )
    .then(
        count=>{
            console.log("resolve 3 작업"); //"resolve 3 작업"
            console.log(count);            // undefined
        },
        reason=>{
            console.log("reject 3 작업");
            console.log(reason);
        }
    )
}
        
```

## async 과 await

<p>
  동기적으로 실행되기 원할때 await 키워드를 통해 기다리게 할 수 있다.<br />
  이 await를 사용하기 위해서는, 해당 비동기 함수를 호출하는 함수가 비동기형이라는것을 명시해줘야한다(async)
</p>


```js
 function getNotice(id){
    console.log("요청");

    return new Promise(resolve =>{
        setTimeout(function(){
            let notice = {id:1, title:"공지사항 prokise", content:"hehe"};
            resolve(notice);

        },10000);
    });

}
(async function(){
  let notice = await getNotice(2); // 오랜시간을 먹는 함수 : 응답없음
  console.log(notice.title); // 결과 값을 가져오면 실행되는 코드
  console.log("기다린다.");
}()); 
 console.log("메인 스레드는 계속 된다.");
```
결과는 "메인 스레드는 계속 된다" - 10초뒤에 "공지사항 prokise" - "기다린다" <br/>

> async는 비동기로 처리되고 async안은 동기적으로 처리된다.

## promise.all()  
여러개의 비동기 처리를 한번에 수행하고 싶을때 사용<br/>

```js
let p1 = 1;
let p2 = new Promise((resolve)=>{
    setTimeout(function(){resolve(200);},1000);
});
let p3 = new Promise((resolve)=>{
    setTimeout(function(){resolve(300);},500);
});

Promise.all([p1,p2,p3])
.then((values=>{
    console.log(values);
    console.log(values[2]);
});
```
